### show tip for route
GET http://localhost:9090/god

### create all tables
PUT http://localhost:9090/god

### fill tables with random data
POST http://localhost:9090/god

### drop all tables and data
DELETE http://localhost:9090/god