###
GET http://localhost:9090/campaign
Content-Type: application/json

{
  "selectedIds": []
}

###
GET http://localhost:9090/campaign
Content-Type: application/json

{
  "selectedIds": [3, 1]
}

###
POST http://localhost:9090/campaign
Content-Type: application/json

{
  "campId": null,
  "name": "ANARCHY",
  "customer": "JOKER",
  "earning": 10000000,
  "spending": 320000,
  "executionStatus": "TESTING-POST"
}

### create all tables
PUT http://localhost:9090/campaign
Content-Type: application/json

{
  "campId": 6,
  "executionStatus": "TESTING-GET"
}

### drop base with id
DELETE http://localhost:9090/campaign
Content-Type: application/json

{
  "selectedIds": [8]
}