### show tip for route
GET http://localhost:9090/random

### create all tables
PUT http://localhost:9090/random

### fill tables with random data
POST http://localhost:9090/random

### drop all tables and data
DELETE http://localhost:9090/random